/* DAYIN SPORT — store.js · catalogue, cart, PDP, checkout (demo data, no backend) */
(()=>{
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const A='/assets/sport/',G='../gen/';
/* ---- catalogue: product lines from dayinsport.com; names, prices and specs are demo placeholders ---- */
const P=[
 {id:'smart-s1',name:'Smart Board S1',cat:'smart',sub:'Bluetooth electronic dartboard · app scoring',price:249,was:289,badge:'Bestseller',imgs:['../gen/sh-hero-product.webp','smart-black-hero.webp','../gen/sh-living-room.webp','smart-glow.webp'],colors:[['Black','#111'],['Graphite','#3b3d44']],opts:{key:'Set',vals:['Board only','Board + 6 darts','Board + cabinet']},rating:4.8,n:0,stock:true,
  bullets:['Bluetooth 5.0 · plays with the DAYIN Sport app and online opponents','15.5" regulation segment area · ultra-thin spider','Auto scoring, 30+ games, voice announcer','Missed-dart catch ring included'],specs:[['Segment area','15.5" (39.4 cm)'],['Connectivity','Bluetooth 5.0'],['Power','USB-C or 3× AA'],['Games','30+'],['Players','1–8 local · online 1v1'],['Weight','2.9 kg'],['Warranty','2 years']],desc:'The board for people who want to play against someone tonight. Pair the app, pick an opponent, throw. Every dart is scored by the segment matrix; every game is saved to your profile.'},
 {id:'arena-15',name:'Arena 15.5″ Electronic Dartboard',cat:'electronic',sub:'Regulation size · LCD scoring · 27 games',price:179,imgs:['electronic-15-a.webp','electronic-15-b.webp','electronic-15-c.webp','../gen/sh-garage.webp'],colors:[['Black','#111'],['Blue','#2f5fbf'],['Red','#c8102e']],opts:{key:'Set',vals:['Board only','Board + 6 darts']},rating:4.7,n:0,stock:true,
  bullets:['Regulation 15.5" segment area','Large LCD, 27 games / 200+ variations','Auto scoring for up to 8 players','Mains adapter included'],specs:[['Segment area','15.5"'],['Display','LCD'],['Games','27 · 200+ variations'],['Players','1–8'],['Power','Mains adapter'],['Weight','2.6 kg'],['Warranty','2 years']],desc:'League-size board with a screen you can read from the oche. Built on the same segment matrix DAYIN supplies to global brands.'},
 {id:'compact-135',name:'Compact 13.5″ Electronic Dartboard',cat:'electronic',sub:'Apartment-size · 24 games',price:119,imgs:['electronic-135-a.webp','electronic-135-red.webp'],colors:[['Black','#111'],['Red','#c8102e']],opts:{key:'Set',vals:['Board only','Board + 6 darts']},rating:4.6,n:0,stock:true,
  bullets:['13.5" segment area — fits a hallway','24 games, 8 players','Battery or adapter','Quiet soft-tip segments'],specs:[['Segment area','13.5"'],['Games','24'],['Players','1–8'],['Power','3× AA or adapter'],['Weight','1.9 kg'],['Warranty','2 years']],desc:'Smaller face, same scoring brain. For the flat, the office, the kids’ room.'},
 {id:'glow-led',name:'Glow LED Dartboard',cat:'smart',sub:'Backlit segments · 7 colour modes · Bluetooth',price:299,badge:'New',imgs:['led-board-color.webp','led-board-red.webp','led-board-bluegreen.webp','../gen/sh-glow.webp'],colors:[['Multi','linear-gradient(135deg,#ff3b30,#ffd60a,#34c759,#0a84ff)']],opts:{key:'Set',vals:['Board only','Board + cabinet']},rating:4.9,n:0,stock:true,
  bullets:['Per-segment LED backlight, 7 colour modes','Hit effects and idle light shows','Bluetooth app scoring & online play','Dimmable for late nights'],specs:[['Segment area','15.5"'],['Lighting','Per-segment RGB LED'],['Connectivity','Bluetooth 5.0'],['Power','Mains adapter'],['Weight','3.4 kg'],['Warranty','2 years']],desc:'The board that turns the lights off in the room. Segment LEDs react to every throw.'},
 {id:'bristle-classic',name:'Bristle Board Classic',cat:'traditional',sub:'Sisal · steel-tip · staple-free bullseye',price:89,imgs:['bristle-board.webp','darts-board-photo.webp'],colors:[['Natural','#c8b48a']],opts:{key:'Set',vals:['Board only','Board + steel darts','Board + surround']},rating:4.7,n:0,stock:true,
  bullets:['Compressed sisal, self-healing','Staple-free bullseye, ultra-thin wire','Rotatable number ring','Tournament 17.75" face'],specs:[['Face','17.75"'],['Material','Sisal'],['Wire','Ultra-thin, staple-free bull'],['Weight','4.5 kg'],['Warranty','1 year']],desc:'Steel-tip the way pubs have always played it. The number ring rotates so the board wears evenly.'},
 {id:'kids-board',name:'Kids Board',cat:'traditional',sub:'Soft-tip · magnetic darts · ages 6+',price:39,badge:'Gift',imgs:['kids-board.webp','../gen/sh-kids.webp'],colors:[['Multi','linear-gradient(135deg,#ff6b6b,#ffd93d,#6bcb77,#4d96ff)']],opts:{key:'Set',vals:['Board + 6 magnetic darts']},rating:4.8,n:0,stock:true,
  bullets:['Magnetic darts — no points','Double-sided: darts and target games','Foldable, hangs anywhere','Ages 6+'],specs:[['Type','Magnetic'],['Darts','6 included'],['Age','6+'],['Weight','0.7 kg']],desc:'The first board. Magnetic darts, two games on two sides, folds flat.'},
 {id:'cabinet-oak',name:'Cabinet Set · Oak',cat:'cabinets',sub:'Solid-wood cabinet · scoreboards · 6 darts',price:349,imgs:['wood-cabinet.webp','cabinet-a.webp','cabinet-b.webp','cabinet-c.webp','../gen/sh-cabinet.webp'],colors:[['Oak','#b48a5a'],['Walnut','#5a3a26'],['Black','#111']],opts:{key:'Board',vals:['With Bristle Classic','With Smart S1','Cabinet only']},rating:4.9,n:0,stock:true,
  bullets:['Solid-wood cabinet, doors with chalk scoreboards','Fits 15.5" and 17.75" boards','Two dart holders, out-chart inside','Wall-mount hardware included'],specs:[['Material','Solid wood'],['Fits','15.5" / 17.75" boards'],['Dimensions','66 × 56 × 10 cm closed'],['Weight','9.8 kg'],['Warranty','2 years']],desc:'Close the doors and it is furniture. Open them and it is a dart night.'},
 {id:'softtip-darts',name:'Soft-Tip Darts · 18 g',cat:'accessories',sub:'Set of 6 · brass barrel · 50 spare tips',price:24,imgs:['dart-impact-dramatic.webp','darts-red-teal.webp','../gen/sh-darts-macro.webp'],colors:[['Red','#c8102e'],['Teal','#1f8a8d'],['Black','#111']],opts:{key:'Weight',vals:['16 g','18 g','20 g']},rating:4.6,n:0,stock:true,
  bullets:['6 darts, brass barrels','50 spare 2BA tips','Standard-shape flights ×2 sets','Case included'],specs:[['Weight','16 / 18 / 20 g'],['Barrel','Brass'],['Thread','2BA'],['Tips','50 spare']],desc:'The darts the boards are tested with.'},
 {id:'scoreboard-module',name:'Scoreboard Module',cat:'accessories',sub:'Add LCD scoring to any bristle board',price:29,imgs:['scoreboard-module.webp'],colors:[['Black','#111']],opts:{key:'Set',vals:['Module only']},rating:4.4,n:0,stock:true,
  bullets:['Manual-entry LCD scorer for steel-tip games','01, Cricket, Count-Up','Battery powered','Wall-mount or shelf'],specs:[['Games','01 · Cricket · Count-Up'],['Power','2× AA'],['Weight','0.3 kg']],desc:'For the bristle board that wants a screen.'},
 {id:'commercial-cabinet',name:'Commercial Dart Machine',cat:'commercial',sub:'Coin-op · 21.5″ screen · for venues',price:0,imgs:['commercial-lineup.webp','tradeshow-cabinet.webp','tradeshow-booth.webp'],colors:[['Black','#111'],['Gold','#c8963e'],['Silver','#b9bcc2']],opts:{key:'Enquiry',vals:['Venue owner','Dealer / operator']},rating:5,n:0,stock:true,quote:true,
  bullets:['Coin-operated electronic dart machines for bars and arcades','21.5" touchscreen, online play, operator tools','Sold through DARTMAN Games and dealers'],specs:[['Type','Coin-op machine'],['Screen','21.5"'],['Sales','Via DARTMAN Games']],desc:'Venue machines are sold through DARTMAN Games and its dealer network — see dartmangames.com.'},
];
const CATS={smart:'Smart & Bluetooth',electronic:'Electronic boards',traditional:'Traditional & kids',cabinets:'Cabinets & sets',accessories:'Darts & accessories',commercial:'Commercial machines'};
const money=n=>'$'+n.toFixed(0);
const img=(p,i=0)=>A+p.imgs[i];
window.STORE={P,CATS};
/* ---- cart ---- */
const KEY='dayinsport-cart-v2';let cart=JSON.parse(localStorage.getItem(KEY)||'[]');
const save=()=>{localStorage.setItem(KEY,JSON.stringify(cart));renderCart();};
const count=()=>cart.reduce((s,i)=>s+i.q,0),subtotal=()=>cart.reduce((s,i)=>s+i.q*i.price,0);
function add(id,opt,color,q=1){const p=P.find(x=>x.id===id);if(!p)return;opt=opt||p.opts.vals[0];color=color||p.colors[0][0];const k=cart.find(i=>i.id===id&&i.opt===opt&&i.color===color);if(k)k.q+=q;else cart.push({id,opt,color,q,price:p.price});save();openDrawer();toast(`${p.name} added`);}
function renderCart(){$$('[data-cart-count]').forEach(e=>{e.textContent=count();e.style.display=count()?'grid':'none';});
  const list=$('.drawer .items');if(!list)return;
  if(!cart.length){list.innerHTML='<div class="emptyc"><p style="font-weight:700;font-size:18px;color:var(--ink)">Your cart is empty.</p><p style="margin-top:6px">Boards, darts, cabinets — pick a lane.</p><a class="btn sm" style="margin-top:18px" href="/shop/collection/">Shop all</a></div>';}
  else list.innerHTML=cart.map((i,k)=>{const p=P.find(x=>x.id===i.id);return `<div class="ci"><img src="${img(p)}" alt=""><div><h4>${p.name}</h4><div class="v">${i.color} · ${i.opt}</div><div class="qty"><button data-q="${k}" data-d="-1" aria-label="Decrease">−</button><output>${i.q}</output><button data-q="${k}" data-d="1" aria-label="Increase">+</button></div><a href="#" class="rm" data-rm="${k}">Remove</a></div><div class="p">${money(i.q*i.price)}</div></div>`}).join('');
  const st=subtotal(),free=150;$('.drawer .ship').innerHTML=st>=free?'<b>✓ Free shipping unlocked</b><div class="bar"><i style="--w:100%"></i></div>':`Add <b>${money(free-st)}</b> more for free shipping<div class="bar"><i style="--w:${Math.min(100,st/free*100)}%"></i></div>`;
  $('.drawer .tot span:last-child').textContent=money(st);$('.drawer .btn.red').toggleAttribute('disabled',!cart.length);
  $$('[data-q]',list).forEach(b=>b.addEventListener('click',()=>{const it=cart[+b.dataset.q];it.q+= +b.dataset.d;if(it.q<=0)cart.splice(+b.dataset.q,1);save();}));
  $$('[data-rm]',list).forEach(b=>b.addEventListener('click',e=>{e.preventDefault();cart.splice(+b.dataset.rm,1);save();}));
  const up=$('.drawer .upsell');if(up){const have=new Set(cart.map(i=>i.id));const s=P.find(p=>p.cat==='accessories'&&!have.has(p.id));up.style.display=s&&cart.length?'':'none';if(s)up.innerHTML=`<span class="k">Complete the set</span><div class="row"><img src="${img(s)}" alt=""><div style="flex:1"><b>${s.name}</b><span>${money(s.price)}</span></div><button class="btn sm ghost" data-add="${s.id}">Add</button></div>`;}
  $$('[data-add]').forEach(b=>{if(!b._w){b._w=1;b.addEventListener('click',e=>{e.preventDefault();add(b.dataset.add);});}});
}
/* drawer */
const drawer=document.createElement('div');drawer.className='drawer';drawer.innerHTML=`<div class="bg"></div><aside class="panel" aria-label="Cart"><header><h3>Your cart</h3><button class="ico" aria-label="Close cart"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 6l12 12M18 6L6 18"/></svg></button></header><div class="items"></div><div class="upsell"></div><div class="ship"></div><footer><div class="tot"><span>Subtotal</span><span>$0</span></div><a class="btn red block lg" href="/shop/checkout/">Checkout</a><p style="font-size:12px;color:var(--muted);text-align:center">Shipping and taxes calculated at checkout · demo store, no payment is taken</p></footer></aside>`;document.body.appendChild(drawer);
const openDrawer=()=>drawer.classList.add('open'),closeDrawer=()=>drawer.classList.remove('open');
$('.bg',drawer).addEventListener('click',closeDrawer);$('header .ico',drawer).addEventListener('click',closeDrawer);
$$('[data-open-cart]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();openDrawer();}));
renderCart();
/* ---- product cards ---- */
function card(p){const badge=p.badge?`<span class="badge ${p.badge==='New'?'red':p.badge==='Gift'?'green':''}">${p.badge}</span>`:'';
  return `<article class="pc rv"><a class="img" href="/shop/product/?p=${p.id}" aria-label="${p.name}">${badge}<img src="${img(p,0)}" alt="${p.name}" loading="lazy">${p.imgs[1]?`<img class="b" src="${img(p,1)}" alt="" loading="lazy">`:''}</a><div class="quick">${p.quote?`<a class="btn sm block white" href="/shop/product/?p=${p.id}">Request a quote</a>`:`<button class="btn sm block white" data-add="${p.id}">Quick add · ${money(p.price)}</button>`}</div><div class="body"><h3><a href="/shop/product/?p=${p.id}">${p.name}</a></h3><div class="sub">${p.sub}</div><div class="row"><span class="price">${p.quote?'Quote':money(p.price)}${p.was?`<s>${money(p.was)}</s>`:''}</span><span class="dots">${p.colors.map(c=>`<i style="background:${c[1]}" title="${c[0]}"></i>`).join('')}</span></div></div></article>`;}
$$('[data-grid]').forEach(g=>{const f=g.dataset.grid;let list=P.filter(p=>f==='featured'?['smart-s1','glow-led','arena-15','cabinet-oak'].includes(p.id):f==='all'?true:p.cat===f);if(g.dataset.exclude)list=list.filter(p=>p.id!==g.dataset.exclude);if(g.dataset.limit)list=list.slice(0,+g.dataset.limit);g.innerHTML=list.map(card).join('');});
/* ---- collection with filters ---- */
const coll=$('[data-collection]');if(coll){const grid=$('.grid',coll),cnt=$('[data-count]',coll),sort=$('select[name=sort]',coll),price=$('input[name=maxprice]',coll),pout=$('[data-maxprice]',coll);
  const url=new URLSearchParams(location.search);const pre=url.get('cat');if(pre){const c=$(`input[name=cat][value="${pre}"]`,coll);c&&(c.checked=true);}
  const q=url.get('q');
  function apply(){const cats=$$('input[name=cat]:checked',coll).map(i=>i.value),feats=$$('input[name=feat]:checked',coll).map(i=>i.value),max=+price.value;pout.textContent=money(max);
    let list=P.filter(p=>(!cats.length||cats.includes(p.cat))&&(p.quote||p.price<=max)&&(!q||(p.name+p.sub).toLowerCase().includes(q.toLowerCase()))&&feats.every(f=>f==='bt'?/bluetooth/i.test(p.sub+p.bullets.join()):f==='led'?/led/i.test(p.name+p.sub):f==='soft'?p.cat!=='traditional'||p.id==='kids-board':true));
    const s=sort.value;list=[...list].sort((a,b)=>s==='low'?a.price-b.price:s==='high'?b.price-a.price:s==='rating'?b.rating-a.rating:0);
    grid.innerHTML=list.length?list.map(card).join(''):'<div class="empty" style="grid-column:1/-1">Nothing matches. Loosen a filter.</div>';cnt.textContent=list.length;bindAdds();reveal();}
  $$('input,select',coll).forEach(i=>i.addEventListener('input',apply));apply();
  const title=$('[data-coll-title]');if(title&&pre&&CATS[pre])title.textContent=CATS[pre];if(title&&q)title.textContent=`“${q}”`;}
/* ---- PDP ---- */
const pdp=$('[data-pdp]');if(pdp){const id=new URLSearchParams(location.search).get('p')||'smart-s1';const p=P.find(x=>x.id===id)||P[0];let color=p.colors[0][0],opt=p.opts.vals[0],qty=1,gi=0;
  document.title=`${p.name} · DAYIN Sport`;
  pdp.innerHTML=`<div class="gal"><div class="main" data-zoom>${p.badge?`<span class="badge">${p.badge}</span>`:''}<img src="${img(p,0)}" alt="${p.name}"></div><div class="thumbs">${p.imgs.map((s,i)=>`<button class="${i?'':'on'}" data-i="${i}" aria-label="Image ${i+1}"><img src="${A+s}" alt=""></button>`).join('')}</div></div>
  <div class="buy"><div class="crumbs"><a href="/shop/">Home</a><span>/</span><a href="/shop/collection/?cat=${p.cat}">${CATS[p.cat]}</a></div><h1>${p.name}</h1><p class="sub">${p.sub}</p>
   <div class="rating" aria-label="Rating">${'★'.repeat(Math.round(p.rating))}<small>Reviews go live with the store — no placeholder reviews shown</small></div>
   <div class="price">${p.quote?'Quote on request':money(p.price)}${p.was?`<s>${money(p.was)}</s>`:''}${p.quote?'':'<small>Demo price · incl. VAT where applicable</small>'}</div>
   <div class="opt"><h4>Colour <b data-color>${color}</b></h4><div class="swatch">${p.colors.map((c,i)=>`<button class="${i?'':'on'}" data-color="${c[0]}" style="--c:${c[1]}" aria-label="${c[0]}"><i></i></button>`).join('')}</div></div>
   <div class="opt"><h4>${p.opts.key} <b data-opt>${opt}</b></h4><div class="opts">${p.opts.vals.map((v,i)=>`<button class="${i?'':'on'}" data-opt="${v}">${v}</button>`).join('')}</div></div>
   ${p.quote?`<a class="btn red lg block" href="/dartman/contact/#quote" target="_blank" rel="noopener">Request a venue quote at DARTMAN Games ↗</a>`:`<div class="atc"><div class="qty"><button data-d="-1" aria-label="Decrease">−</button><output>1</output><button data-d="1" aria-label="Increase">+</button></div><button class="btn red lg" style="flex:1" data-atc>Add to cart · <span data-total>${money(p.price)}</span></button></div>`}
   <div class="stock"><i></i>In stock · ships in 1–2 working days from Dongguan <span style="color:var(--muted);font-weight:400">(demo)</span></div>
   <div class="perks"><div><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 7h13v10H3zM16 10h4l1 3v4h-5"/><circle cx="7" cy="18" r="1.5"/><circle cx="18" cy="18" r="1.5"/></svg>Free shipping over $150</div><div><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3l8 4v5c0 5-3.5 8-8 9-4.5-1-8-4-8-9V7z"/></svg>2-year warranty · made by DAYIN, the OEM behind 50+ brands</div><div><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 12a8 8 0 0 1 14-5l2 2M20 12a8 8 0 0 1-14 5l-2-2"/></svg>30-day returns</div></div>
   <div class="acc"><details open><summary>Overview</summary><p>${p.desc}</p><ul style="margin:10px 0 0;padding-left:18px">${p.bullets.map(b=>`<li>${b}</li>`).join('')}</ul></details><details><summary>Specifications</summary><table class="spec">${p.specs.map(s=>`<tr><td>${s[0]}</td><td>${s[1]}</td></tr>`).join('')}</table></details><details><summary>In the box</summary><p>${p.name}, mounting hardware, quick-start guide${/dart/i.test(opt)?', darts as selected':''}.</p></details><details><summary>Shipping &amp; returns</summary><p>Ships from DAYIN’s Dongguan warehouse. 30-day returns in original packaging. Demo store — no orders are processed.</p></details></div>
  </div>`;
  const main=$('.gal .main img',pdp);$$('.thumbs button',pdp).forEach(b=>b.addEventListener('click',()=>{gi=+b.dataset.i;main.src=A+p.imgs[gi];$$('.thumbs button',pdp).forEach(x=>x.classList.toggle('on',x===b));}));
  $$('.swatch button',pdp).forEach(b=>b.addEventListener('click',()=>{color=b.dataset.color;$('[data-color]',pdp).textContent=color;$$('.swatch button',pdp).forEach(x=>x.classList.toggle('on',x===b));}));
  $$('.opts button',pdp).forEach(b=>b.addEventListener('click',()=>{opt=b.dataset.opt;$('[data-opt]',pdp).textContent=opt;$$('.opts button',pdp).forEach(x=>x.classList.toggle('on',x===b));}));
  $$('.qty button',pdp).forEach(b=>b.addEventListener('click',()=>{qty=Math.max(1,qty+ +b.dataset.d);$('.qty output',pdp).textContent=qty;$('[data-total]',pdp).textContent=money(p.price*qty);}));
  $('[data-atc]',pdp)?.addEventListener('click',()=>add(p.id,opt,color,qty));
  const rel=$('[data-related]');if(rel){rel.innerHTML=P.filter(x=>x.id!==p.id&&(x.cat===p.cat||x.cat==='accessories')).slice(0,4).map(card).join('');}
  const cmp=$('[data-compare]');if(cmp){const rows=[['Segment area',x=>x.specs.find(s=>/segment|face/i.test(s[0]))?.[1]||'—'],['Bluetooth / app',x=>/bluetooth/i.test(x.sub+x.bullets.join())?'y':'n'],['LED backlight',x=>/led/i.test(x.name+x.sub)?'y':'n'],['Players',x=>x.specs.find(s=>s[0]==='Players')?.[1]||'—'],['Price',x=>x.quote?'Quote':money(x.price)]];const set=P.filter(x=>['smart-s1','glow-led','arena-15','compact-135'].includes(x.id));
    cmp.innerHTML=`<table><thead><tr><th></th>${set.map(x=>`<th>${x.name}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td style="color:var(--muted)">${r[0]}</td>${set.map(x=>{const v=r[1](x);return v==='y'?'<td class="y">✓</td>':v==='n'?'<td class="n">—</td>':`<td>${v}</td>`}).join('')}</tr>`).join('')}</tbody></table>`;}
}
/* ---- checkout ---- */
const co=$('[data-checkout]');if(co){const steps=$$('.fstep',co),crumbs=$$('.steps span',co);let i=0;const sum=$('.summ',co);
  function renderSum(){const st=subtotal(),ship=st>=150||!st?0:12,tax=0;sum.innerHTML=`${cart.map(it=>{const p=P.find(x=>x.id===it.id);return `<div class="ci"><img src="${img(p)}" alt=""><div><h4>${p.name}</h4><div class="v">${it.color} · ${it.opt} · ×${it.q}</div></div><div class="p">${money(it.q*it.price)}</div></div>`}).join('')||'<p style="color:var(--muted)">Cart is empty.</p>'}<div class="l"><span>Subtotal</span><span>${money(st)}</span></div><div class="l"><span>Shipping</span><span>${ship?money(ship):'Free'}</span></div><div class="l"><span>Taxes</span><span>Calculated by country</span></div><div class="tot"><span>Total</span><span>${money(st+ship)}</span></div><p style="font-size:12px;color:var(--muted)">Demo checkout — no payment is processed and nothing is shipped.</p>`;}
  const show=()=>{steps.forEach((s,k)=>s.classList.toggle('on',k===i));crumbs.forEach((c,k)=>c.classList.toggle('on',k===i));};
  $$('[data-next]',co).forEach(b=>b.addEventListener('click',()=>{const st=steps[i];let ok=true;$$('[required]',st).forEach(r=>{const bad=!r.value.trim()||(r.type==='email'&&!/^\S+@\S+\.\S+$/.test(r.value));r.closest('label')?.classList.toggle('invalid',bad);if(bad)ok=false;});if(!ok)return toast('Please complete the highlighted fields.');
    if(i===steps.length-2){$('[data-order]',co).textContent='DS-'+Math.floor(100000+Math.random()*900000);cart=[];save();}i=Math.min(steps.length-1,i+1);show();}));
  $$('[data-prev]',co).forEach(b=>b.addEventListener('click',()=>{i=Math.max(0,i-1);show();}));
  renderSum();show();}
/* ---- search ---- */
const sBox=$('.search');if(sBox){const inp=$('input',sBox),res=$('.res',sBox);$$('[data-open-search]').forEach(b=>b.addEventListener('click',()=>{sBox.classList.add('open');inp.focus();}));$('.ico',sBox).addEventListener('click',()=>sBox.classList.remove('open'));
  inp.addEventListener('input',()=>{const q=inp.value.trim().toLowerCase();res.innerHTML=q?P.filter(p=>(p.name+' '+p.sub).toLowerCase().includes(q)).slice(0,6).map(p=>`<a href="/shop/product/?p=${p.id}"><img src="${img(p)}" alt=""><div><b>${p.name}</b><div style="font-size:13px;color:var(--muted)">${p.sub}</div></div><span style="margin-left:auto;font-weight:700">${p.quote?'Quote':money(p.price)}</span></a>`).join('')||'<div style="padding:16px;color:var(--muted)">No matches.</div>':'';});
  inp.addEventListener('keydown',e=>{if(e.key==='Enter'){location.href='/shop/collection/?q='+encodeURIComponent(inp.value);}if(e.key==='Escape')sBox.classList.remove('open');});}
/* ---- ui ---- */
function bindAdds(){$$('[data-add]').forEach(b=>{if(!b._w){b._w=1;b.addEventListener('click',e=>{e.preventDefault();add(b.dataset.add);});}});}bindAdds();
function toast(m){let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t);}t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),3000);}window.toast=toast;
const burger=$('.burger'),mnav=$('.mnav');burger&&burger.addEventListener('click',()=>{const o=!mnav.classList.contains('open');mnav.classList.toggle('open',o);document.body.classList.toggle('menu-open',o);});
/* motion */
gsap.registerPlugin(ScrollTrigger,SplitText);
function reveal(){$$('.rv:not(.in)').forEach(el=>ScrollTrigger.create({trigger:el,start:'top 92%',once:true,onEnter:()=>el.classList.add('in')}));}reveal();
if(!reduce){$$('[data-split]').forEach(h=>{const st=new SplitText(h,{type:'lines',linesClass:'line'});gsap.set(st.lines,{yPercent:100,opacity:0});gsap.to(st.lines,{yPercent:0,opacity:1,duration:1,stagger:.09,ease:'expo.out',delay:.1});});}
/* hero tilt */
const tilt=$('.prod3d');if(tilt&&matchMedia('(pointer:fine)').matches&&!reduce){const card=$('.card',tilt);addEventListener('pointermove',e=>{const r=tilt.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;gsap.to(card,{rotateY:x*22,rotateX:-y*18,duration:.6,ease:'power2.out'});});}
$$('.marquee .track').forEach(t=>t.innerHTML+=t.innerHTML);
const lb=document.createElement('div');lb.className='lb';lb.innerHTML='<img alt="">';document.body.appendChild(lb);lb.addEventListener('click',()=>lb.classList.remove('open'));$$('[data-zoom]').forEach(z=>z.addEventListener('click',()=>{lb.querySelector('img').src=$('img',z).src;lb.classList.add('open');}));
$$('form[data-demo]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();toast(f.dataset.demo);f.reset();}));
$$('[data-year]').forEach(e=>e.textContent=new Date().getFullYear());
})();
